#import "@preview/tidy:0.4.3": *

#set page(paper: "us-trade", margin: 0.75in)
#set par(justify: true)
#set text(font: "Libertinus Serif", size: 10pt)

#let number-until-with(max-level, schema) = (..numbers) => {
  if numbers.pos().len() <= max-level {
    numbering(schema, ..numbers)
  }
}

#set heading(numbering: number-until-with(2, "1.1"))

#show heading.where(level: 1): it => [#set text(size: 14pt);#v(12pt);#it;#v(6pt)]
#show heading.where(level: 2): it => [#set text(size: 12pt);#it;#v(4pt)]
#show heading.where(level: 3): it => [#set text(size:  8pt);#it.body;#v(1pt)]

#let pkg-meta = toml("typst.toml")
#let this-pkg = pkg-meta.package

#let pkg-ver = [#raw(this-pkg.name + "-" + this-pkg.version)]

#set document(
  title: [Package API documentation for #pkg-ver],
  author: this-pkg.authors,
  description: [Package API documentation for #pkg-ver],
  keywords: this-pkg.keywords,
  date: datetime.today(),
)

#show title: it => {
  set text(size: 17pt)
  set align(center)
  block(width: 60%, height: 48pt)[
    #align(center + horizon)[#it]
  ]
}

#show "->": text(font: "Libertinus Serif")[#sym.arrow.r]

#title()

#align(center)[#grid(
    columns: (40%),
    align(center)[
      #set text(size: 0.8em)
      C. Naaktgeboren \
      #link("https://github.com/cnaak/canyon.typ")
    ],
  )
]
#v(1em)

#import "@preview/untypsignia:0.1.1": *

#let typst() = [#text(font: "Buenard", hyphenate: false)[#typstmark()]]

= Canyon's End User in Full Control Approach

Mainstream #typst() templates are written so as to bring functionality and to be used in an
`#import` then `#show` workflow; however, that frequently comes at the cost of introducing (i)
new syntax and (ii) opaque template-side code and settings.

Any template end user that had the need to customize things not anticipated or provided for by
the template's author have experienced this shortcoming.

Canyon (`canyon-0.1.0`) explores a different approach in which a new canyon-based document is a
book _stencil_ that users can freely edit and adapt, with:

- _No_ opaque template-side code or settings;
- _No_ canyon `#import` statements;
- _No_ canyon-specialized `#show` rules;
- _Full access_ to the entire #typst() project;
- The _familiar_ #typst() syntax to work with; and
- Full _separation of concepts_ for (i) metadata, (ii) configuration, (iii) elements, (iv)
  layout, and (v) contents.

Therefore, canyon users have access to _all_ document settings as if they had manually started
writing the document from scratch on their own---except they hadn't!---and thus have _full
access_ to everything #typst() in that project.

= Overview

Out-of-the-box canyon books come with the following:

+ (i) Front-matter; (ii) Body; and (iii) Back-matter book structure;
+ (i) Cover page, and (ii) numbered Chapter page images;
+ All `#set` and `#show` rules are accessible; hence, customizable;
+ The "openright" chapter pagination—through `#pagebreak(to: "odd")`;
+ Front-matter with Title pages; Credits; Contents; List of Figures, Tables, Equations, and Exhibits; and a Preface;
+ Book body with regular Chapters (single Part);
+ Back-matter with Appendix, Bibliography, Glossary, Index, and Discalimers;
+ Figures, Tables, Exhibits, Problems, and Equations are Chapter-numbered: `1.1` instead of `1`, with configurable separators by type _group_, i.e., a separate one for:  (i) Equations, (ii) Figures and Tables, (iii) Exhibits, and (iv) Problems;
+ A simple and configurable 3-color system with: (i) a thematic color (default: _dark indigo_), (ii) a page background color (default: _light sepia_), and (iii) a cover text color (default: _dark indigo_).

A _selection_ of canyon book pages using default settings are grouped in the thumbnail below:

#figure(
  caption: "Selection of canyon pages, showing, in order: (i)\u{A0}the half-title and (ii)\u{A0}title pages, (iii)\u{A0}contents, (iv)\u{A0}preface\u{2014}as book front-matter\u{2014}as well as sample (v)\u{A0}book body and (vi)\u{A0}back-matter pages",
)[
  #image("thumbnail.png", width: 50%)
]




/*
= Package Self Documentation

The sections below are automatically generated by `tidy-0.4.3` based on the source code
documentation annotations on #pkg-ver.

#import "canyon.typ"
#let api = parse-module(
  read("???.typ"),
  name: this-pkg.name,
  scope: (canyon: canyon),
  preamble: "\n"
)

#show-module(
  api,
  style: styles.default,
  first-heading-level: 1,
)
*/

